CREATE DATABASE IF NOT EXISTS BD_VENTAS;

CREATE TABLE PERFILES(
COD_PERFIL INT NOT NULL AUTO_INCREMENT,
NOM_PERFIL VARCHAR(50) NOT NULL,
PRIMARY KEY(COD_PERFIL)
);

CREATE TABLE USUARIOS(
COD_USUARIO INT NOT NULL AUTO_INCREMENT,
NOM_USUARIO VARCHAR(50) NOT NULL,
APP_USUARIO VARCHAR(50) NOT NULL,
APM_USUARIO VARCHAR(50) NOT NULL,
DNI_USUARIO INT(8) NOT NULL,
CEL_USUARIO INT(9) NOT NULL,
DIR_USUARIO VARCHAR(70) NOT NULL,
COD_PERFIL INT NOT NULL,
PRIMARY KEY(COD_USUARIO),
CONSTRAINT fk_usuarios FOREIGN KEY (COD_PERFIL) REFERENCES PERFILES(COD_PERFIL) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE CATEGORIAS(
COD_CATEGORIA INT NOT NULL AUTO_INCREMENT,
NOM_CATEGORIA VARCHAR(50) NOT NULL,
PRIMARY KEY (COD_CATEGORIA)
);

CREATE TABLE PRODUCTOS(
COD_PRODUCTO INT NOT NULL AUTO_INCREMENT,
NOM_PRODUCTO VARCHAR(50) NOT NULL,
DES_PRODUCTO VARCHAR(50) NOT NULL,
STK_PRODUCTO INT NOT NULL,
PREVEN_PRODUCTO FLOAT NOT NULL ,
PRECOM_PRODUCTO FLOAT NOT NULL,
COD_CATEGORIA INT NOT NULL,
PRIMARY KEY (COD_PRODUCTO),
CONSTRAINT fk_productos FOREIGN KEY (COD_CATEGORIA) REFERENCES CATEGORIAS(COD_CATEGORIA) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE VENTAS(
COD_VENTA INT NOT NULL AUTO_INCREMENT,
NUM_VENTA INT NOT NULL,
CANT_VENTA INT NOT NULL,
PREUNI_VENTA FLOAT NOT NULL,
TOTAL_VENTA FLOAT NOT NULL,
COD_PRODUCTO INT NOT NULL,
PRIMARY KEY(COD_VENTA),
CONSTRAINT fk_ventas FOREIGN KEY (COD_PRODUCTO) REFERENCES PRODUCTOS(COD_PRODUCTO) ON DELETE CASCADE ON UPDATE CASCADE
);


INSERT INTO perfiles (cod_perfil,nom_perfil) VALUES (0,'Admin');
INSERT INTO perfiles (cod_perfil,nom_perfil) VALUES (0,'Vendedor');

INSERT INTO usuarios (cod_usuario,nom_usuario,app_usuario,apm_usuario,dni_usuario,cel_usuario,dir_usuario,cod_perfil) 
VALUES (0,'Jorge','Mayta','Mendoza',70829173,951622833,'Av. Aurelio Garcia y Garcia',1);

INSERT INTO categorias (cod_categoria,nom_categoria) VALUES (0,'GASEOSAS');
INSERT INTO categorias (cod_categoria,nom_categoria) VALUES (0,'GALLETAS');
INSERT INTO categorias (cod_categoria,nom_categoria) VALUES (0,'VINOS');
INSERT INTO categorias (cod_categoria,nom_categoria) VALUES (0,'CERVEZAS');


INSERT INTO productos (cod_producto,nom_producto,des_producto,stk_producto,preven_producto,precom_producto,cod_categoria)
VALUES (0,'Fanta 500ml','Gaseosa sabor a naranja',10,2.20,1.80,1);